[tool.poetry]
name = "luiza"
version = "0.1.0"
description = "luiza landing"
authors = ["Miron Syrov <mironsyrovedu@gmail.com>"]
readme = "README.md"
packages = [
    { include = "src" },
    { include = "*", from = "src" }
]
include = ["README.md", "poetry.lock", ".venv/**/*"]

[tool.poetry.dependencies]
python = "^3.12,<3.14"
flask = "^3.1.0"
flask-sqlalchemy = "^3.1.1"
flask-login = "^0.6.3"
python-dotenv = "^1.2.1"
flask-wtf = "^1.2.2"
email-validator = "^2.3.0"
psycopg2-binary = "^2.9.11"
uwsgi = "^2.0.31"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
